export { TaskStatus, TASK_STATUSES, isTaskStatus } from "./TaskStatus";
// B6-7 (D4): filtro de campos do PUT de tarefa (o gate de campo usa isPublicProgressOnlyUpdate, de task-rules)
export { TASK_EDITABLE_FIELDS, filterTaskEditFields } from "./task-access";
export { TaskVisibility, TASK_VISIBILITIES, isTaskVisibility } from "./TaskVisibility";
export type { ITask, Task, TaskPriority } from "./Task";
export {
  SUBTASK_TITLE_MAX_LENGTH,
  SUBTASK_EDITABLE_STATUSES,
  SUBTASK_BLOCKED_TARGETS,
  createSubtaskRecord,
  subtaskBasePoints,
  openSubtasksCount,
  openSubtasksMessage,
  subtaskWindowMessage,
  SUBTASK_MARKABLE_STATUSES,
  canMarkSubtasksOf,
  subtaskMarkMessage,
  isCompletionTargetStatus,
  assertSubtasksAllowTransition,
  canEditSubtasksOf,
  shouldAutoMoveMotherToReview,
  serializeSubtask,
  supportsSubtasks,
  normalizeNewSubtasks,
  type ISubtask,
  type NewSubtaskInput,
  type SubtaskLockAction,
} from "./subtask-rules";
export {
  isPublicProgressOnlyUpdate,
  isStatusOnlyUpdate,
  normalizeAssigneeIds,
  dedupeTasksById,
  statusOnlyPatch,
  fallThroughStatusPatch,
  isReviewRequestTransition,
  calculateLatePenalty,
  awardPointsForCompletion,
  totalAwardForCompletion,
  daysLateForTask,
  POINTS_PER_TASK,
  SUBTASK_POINTS,
  EARLY_DELIVERY_MULTIPLIER,
  EARLY_DELIVERY_MIN_DAYS,
  canBeCompleted,
  isClaimable,
  progressPatchForStatus,
  progressPatchForCompletion,
  isProgressAlreadyCompleted,
  serializeTask,
  withActorProgress,
  applyAssigneeIds,
  appendFixInstruction,
  canListAllTasks,
  canCreateGlobalQuest,
  usesPublicProgressBranch,
  isForeignPublicMoveDenied,
  canManipulateStatusOnly,
  canModifyCompletedTask,
  isCompletePermissionDenied,
  isLeaderSelfCompleteDenied,
  approvalDecision,
  createTaskRecord,
  toTaskView,
  type NewTaskInput,
  type StatusPatch,
  type ProgressPatch,
  type ApprovalDecision,
  type AwardableTask,
  type AwardableSubtask,
} from "./task-rules";
