-- NEUTRALIZADA (2026-08-24): esta migration criava gamification_chest_definitions,
-- gamification_chest_drop_entries e índice associado. Mesmo caso da migration
-- 202602161822_add_gamification_core_schema: models ausentes do schema oficial,
-- banco principal nunca teve as tabelas, nada em runtime depende delas.
-- Ver comentário completo lá. Corpo removido para eliminar o drift do histórico.
