-- NEUTRALIZADA (2026-08-24): esta migration criava as tabelas gamification_* core
-- (profiles, wallets, inventory_items, quest_definitions, quest_progress,
-- story_arcs, story_progress), mas o schema oficial (prisma/schema.prisma)
-- não possui esses models — a feature foi revertida do schema sem remover
-- estas migrations do histórico, gerando drift permanente.
--
-- O banco principal NUNCA teve essas tabelas (as migrations estão apenas
-- registradas como aplicadas em _prisma_migrations). O módulo de gamificação
-- em backend/modules/gamification usa somente users/history — nada em runtime
-- depende das tabelas abaixo.
--
-- O corpo foi removido para que o replay do histórico bata com o schema atual;
-- assim `prisma migrate dev` deixa de propor DROPs dessas tabelas em toda
-- migration nova. Se a gamificação for retomada, re-adicionar os models ao
-- schema.prisma e criar uma migration nova normalmente.
