/**
 * Permission + feature matrices — pure domain (SPEC §4.3).
 *
 * PERMISSIONS is the BACKEND authority (was `lib/auth/rbac.ts`). FEATURE_ACCESS is the
 * feature/UI-visibility map (was `lib/auth/features.ts`). Both live here now so the
 * authorisation rule is a domain artefact, not something a route or a component composes.
 *
 * The shared-key parity invariant between the two maps is already guarded by
 * tests/unit/rbac-contract.test.ts; rbac-policy.test.ts freezes the full matrices.
 * Values are a verbatim copy — any change here is a behaviour change and needs a decision.
 */
import type { Role } from "./roles";

export const PERMISSIONS = {
  MANAGE_USERS: ["COORDENADOR", "GERENTE"],
  MANAGE_NOTIFICATIONS: ["COORDENADOR", "GERENTE"],
  MANAGE_REWARDS: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  MANAGE_PURCHASES: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  MANAGE_WORK_SESSIONS: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  MANAGE_PROJECTS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO"],
  MANAGE_PROJECT_MEMBERS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO"],
  MANAGE_TASKS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO", "COLABORADOR", "PESQUISADOR"],
} as const satisfies Record<string, Role[]>;

export type Permission = keyof typeof PERMISSIONS;

export const FEATURE_ACCESS = {
  DASHBOARD_ADMIN: ["COORDENADOR", "GERENTE"],
  DASHBOARD_WEEKLY_REPORTS: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  DASHBOARD_PROJETOS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO", "PESQUISADOR", "COLABORADOR"],
  VIEW_PROJECT_DASHBOARD: [
    "COORDENADOR",
    "GERENTE",
    "GERENTE_PROJETO",
    "PESQUISADOR",
    "COLABORADOR",
    "VOLUNTARIO",
  ],
  MANAGE_REWARDS: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  MANAGE_USERS: ["COORDENADOR", "GERENTE"],
  MANAGE_PROJECTS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO"],
  MANAGE_TASKS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO", "COLABORADOR", "PESQUISADOR"],
  MANAGE_PROJECT_MEMBERS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO"],
  MANAGE_SCHEDULE: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  MANAGE_BADGES: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  VIEW_ALL_DATA: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  VIEW_WEEKLY_REPORTS: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  EDIT_PROJECT: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO"],
  EDIT_TASKS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO", "COLABORADOR"],
  CREATE_TASK: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO", "COLABORADOR", "PESQUISADOR"],
  CREATE_PROJECT: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO"],
  MANAGE_LABORATORY: ["COORDENADOR", "LABORATORISTA"],
  ASSUME_LAB_RESPONSIBILITY: ["COORDENADOR", "LABORATORISTA"],
  COMPLETE_PUBLIC_TASKS: ["VOLUNTARIO", "COLABORADOR", "GERENTE_PROJETO", "COORDENADOR", "GERENTE"],
  ASSIGN_TASKS_TO_VOLUNTEERS: ["COORDENADOR", "GERENTE", "GERENTE_PROJETO", "COLABORADOR"],
  APPROVE_USERS: ["COORDENADOR", "LABORATORISTA"],
  APPROVE_PURCHASES: ["COORDENADOR", "GERENTE", "LABORATORISTA"],
  VIEW_ALL_LOGS: ["COORDENADOR"],
  EDIT_OWN_LOGS: [
    "COORDENADOR",
    "LABORATORISTA",
    "GERENTE",
    "GERENTE_PROJETO",
    "COLABORADOR",
    "VOLUNTARIO",
  ],
} as const satisfies Record<string, Role[]>;

export type FeatureAccess = keyof typeof FEATURE_ACCESS;

export const PERMISSION_KEYS = Object.keys(PERMISSIONS) as Permission[];
export const FEATURE_KEYS = Object.keys(FEATURE_ACCESS) as FeatureAccess[];
